### PR TITLE
Added Symbols: Block 2.X.1.1 and Penetrate 2.X.1.17

### PR DESCRIPTION
**Pull request by wcmatthysen**
### Description of the Change
Created a new-pull request from the changes in upstream pull-request [#134](https://github.com/NASAWorldWind/WorldWindJava/pull/134). New symbols namely Block 2.X.1.1 and Penetrate 2.X.1.17 were added by @mziolkowski.

### Why Should This Be In Core?
The Tactical Graphic database should be larger.

### Benefits
Another useful symbol in the code.

### Potential Drawbacks
None

### Applicable Issues
None

### CODE REVIEW

**Comment by wcmatthysen** [comment]
Note: this is not ready to merge yet. I picked up a bug when running the `TacticalGraphics` example. When the positions of the penetrate symbol is swapped with the block symbol so that the penetrate symbol's orientation is rotated 180-degrees the arrows are incorrectly drawn. We need to fix this before we can merge. We should also probably add setter methods to control the arrow's angle and lengths. This is  present if you look at the `AttackByFirePosition` class.

**Comment by ComBatVision** [comment]
Hi @wcmatthysen,

Any news about this PR status?

**Comment by wcmatthysen** [comment]
> Hi @wcmatthysen,
> 
> Any news about this PR status?

Hi @ComBatVision, you can have a look at the code and fix it up if you need it in your project. I'm not working on WorldWind at this point in time anymore.

**Comment by gbburkhardt** [comment]
@ComBatVision:  please merge this.  You might want to give me merge privileges.  Thanks.

**Comment by ComBatVision** [comment]
I have merged it. I will give you privileges later. Now I am little bit
busy.

вт, 27 груд. 2022, 19:25 користувач Glenn Burkhardt <
***@***.***> пише:

**Comment by gbburkhardt** [comment]
Superseded by pull request 81.

**Pull request closed without merging**
